name: CVC5 Commit Coverage Analysis

on:
  workflow_dispatch:

jobs:
  commit-coverage-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Install LLVM/Clang 17
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '17'

      - name: Add LLVM to PATH
        run: echo "${{ env.LLVM_PATH }}/bin" >> $GITHUB_PATH

      - name: Export LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=${{ env.LLVM_PATH }}/lib" >> $GITHUB_ENV

      - name: Verify Clang
        run: |
          clang++ --version
          clang -print-resource-dir
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Download coverage mapping artifact from latest successful run
        uses: dawidd6/action-download-artifact@v3
        with:
          name: coverage-mapping-final
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: cvc5-coverage-analysis.yml
      
      - name: Extract coverage mapping
        run: |
          gunzip coverage_mapping_merged.json.gz
          ls -la coverage_mapping_merged.json
      
      - name: Install Python dependencies
        run: |
          pip install gitpython unidiff "libclang==17.0.6"

      - name: Verify libclang Python binding and library
        run: |
          python - <<'PY'
          import os
          from clang import cindex
          from clang.cindex import Config
          print('clang module:', cindex.__file__)
          print('LIBCLANG_PATH env:', os.environ.get('LIBCLANG_PATH'))
          try:
              print('loaded lib:', Config.loaded_library)
          except Exception:
              # Force load from LIBCLANG_PATH if not yet loaded
              libdir = os.environ.get('LIBCLANG_PATH')
              if libdir:
                  import sys
                  import pathlib
                  cand = pathlib.Path(libdir) / 'libclang.so'
                  try:
                      Config.set_library_file(str(cand))
                      print('loaded lib:', Config.loaded_library)
                  except Exception as e:
                      print('load failed:', e)
              else:
                  print('LIBCLANG_PATH not set')
          PY
      
      - name: Run commit coverage analysis
        working-directory: cvc5
        run: ${{ github.workspace }}/scripts/cvc5/run_commit_coverage_analysis.sh 15 ${{ github.workspace }}/scripts/cvc5/commit_coverage_analyzer.py ../coverage_mapping_merged.json

      - name: Build signature dumper (LibTooling)
        working-directory: cvc5
        run: |
          # Copy the tool source into this repo workspace to build against compile_commands.json
          cp ${{ github.workspace }}/scripts/cvc5/sig_dump.cpp ./sig_dump.cpp
          # Build using installed LLVM/Clang
          clang++ -std=c++17 $(llvm-config --cxxflags) sig_dump.cpp -o sig_dump $(llvm-config --ldflags --system-libs --libs clangTooling clangASTMatchers clangFrontend clangAST clangBasic)

      - name: Run signature dumper on changed files (HEAD)
        working-directory: cvc5
        run: |
          # Collect changed C/C++ files for HEAD commit in src/
          CHANGED=$(git show --name-only --pretty=format: HEAD | grep '^src/.*\.[ch]p\{0,2\}$' || true)
          if [ -n "$CHANGED" ]; then
            ./sig_dump -p build $CHANGED | head -200
          else
            echo "No changed C/C++ files in HEAD to dump signatures for."
          fi
