name: CVC5 Regression Tests

on:
  workflow_dispatch:

jobs:
  build-cvc5:
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build.outcome }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        id: build
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Upload CVC5 build
        uses: actions/upload-artifact@v4
        with:
          name: cvc5-build
          path: cvc5/
          retention-days: 1

  regress0:
    needs: build-cvc5
    runs-on: ubuntu-latest
    if: needs.build-cvc5.outputs.build-success == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Download CVC5 build
        uses: actions/download-artifact@v4
        with:
          name: cvc5-build
          path: ./
      
      - name: Run regress0 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress0

  regress1:
    needs: build-cvc5
    runs-on: ubuntu-latest
    if: needs.build-cvc5.outputs.build-success == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Download CVC5 build
        uses: actions/download-artifact@v4
        with:
          name: cvc5-build
          path: ./
      
      - name: Run regress1 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress1

  regress2:
    needs: build-cvc5
    runs-on: ubuntu-latest
    if: needs.build-cvc5.outputs.build-success == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Download CVC5 build
        uses: actions/download-artifact@v4
        with:
          name: cvc5-build
          path: ./
      
      - name: Run regress2 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress2

  regress3:
    needs: build-cvc5
    runs-on: ubuntu-latest
    if: needs.build-cvc5.outputs.build-success == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Download CVC5 build
        uses: actions/download-artifact@v4
        with:
          name: cvc5-build
          path: ./
      
      - name: Run regress3 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress3

  regress4:
    needs: build-cvc5
    runs-on: ubuntu-latest
    if: needs.build-cvc5.outputs.build-success == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Download CVC5 build
        uses: actions/download-artifact@v4
        with:
          name: cvc5-build
          path: ./
      
      - name: Run regress4 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress4
