name: CVC5 Regression Tests

on:
  workflow_dispatch:

jobs:

  regress0:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Run regress0 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress0

  regress1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Run regress1 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress1

  regress2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Run regress2 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress2

  regress3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Run regress3 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress3

  regress4:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build CVC5 with coverage
        run: |
          ./scripts/cvc5/build.sh --coverage
      
      - name: Run regress4 tests with timing
        run: |
          cd cvc5/build
          ../../scripts/measure_time.sh ../../scripts/cvc5/run_regression_tests.sh regress4
